feat: IDP-1116 generazione-qr-code-magic-link-portale-esercenti
pagopa/cstar-infrastructure pull request #1002
Opened 2023-06-21 14:11 UTC by LarissaASLeite

### List of changes

Add alert CreateTransaction
Update alert CosmosServerSideRetry

### Motivation and context

### Type of changes

- [x] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

#### Has This Been Tested?

- [x] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [ ] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### If PR is partially applied, why? (reserved to mantainers)

2023-06-21 14:20 UTC, marco-di-lisa submitted a review, later dismissed

2023-06-22 08:59 UTC, GiovanniMancini commented on src/domains/idpay-app/12_alert.tf
> +resource "azapi_resource" "alert_CreateTransaction" {
@larissaaiala The system has migrated to azurerm version 3. Could you check if you can use a better, more specific resource to create the alarm?

2023-06-22 09:27 UTC, GiovanniMancini requested changes
The domain has migrated to version 3 of azurerm provider. Maybe a more specific resource could be used to create alarms.

2023-06-22 13:07 UTC, antonioT90 approved these changes

2023-06-23 12:42 UTC, merged