fix: [IDP-1281] fix swagger IO
pagopa/cstar-infrastructure pull request #1013
Opened 2023-06-26 10:46 UTC by frtrinca

### List of changes

fix swagger
### Motivation and context

### Type of changes

- [ ] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

#### Has This Been Tested?

- [x] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [x] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### If PR is partially applied, why? (reserved to mantainers)

2023-06-26 12:33 UTC, gammam requested changes
@frtrinca TransactionDetailDTO non dovrebbe cambiare tra sconto e rimborso. 
La diversa presentazione deve essere gestita dal client
facciamo un check

2023-06-26 12:53 UTC, mastro993 approved these changes

2023-06-26 13:01 UTC, mastro993 commented
> @frtrinca TransactionDetailDTO non dovrebbe cambiare tra sconto e rimborso. La diversa presentazione deve essere gestita dal client facciamo un check

Non è solo una questione di presentazione, se ci arriva l'oggetto e non rispetta le specifiche fallisce il decoder e mostriamo un errore. 

Dopo esserci sentiti io e @frtrinca  abbiamo convenuto che per risolvere il problema ci sono due strade:
- Inserire i valori come opzionali, quindi poter inviare dei DTO senza i dati e fare passare il decoder
- Discriminare l'oggetto e dividerlo in due oggetti differenti, uno per `refund` e uno per `discount`, in modo da poter avere tutti i valori come required.

Per questioni di tempistiche si è deciso di proseguire prima con la prima strada e poi, successivamente, con la seconda.

2023-06-26 13:53 UTC, diegolagospagopa approved these changes

2023-06-26 15:36 UTC, diegolagospagopa approved these changes

2023-06-26 15:37 UTC, mastro993 approved these changes

2023-06-27 08:34 UTC, gammam commented
we need to exclude code review

2023-06-27 08:34 UTC, merged