Update swagger timeline
pagopa/cstar-infrastructure pull request #1018
Opened 2023-06-27 16:58 UTC by frtrinca

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

#### Has This Been Tested?

- [ ] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [ ] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### If PR is partially applied, why? (reserved to mantainers)

2023-06-28 15:18 UTC, mastro993 requested changes
Alcune modifiche non sono presenti nello YAML full. Noi andremo ad utilizzare quello. Potete aggiornarlo? Grazie

2023-06-28 15:51 UTC, mastro993 approved these changes

2023-07-04 09:29 UTC, gammam approved these changes

2023-07-04 09:35 UTC, GiovanniMancini approved these changes

2023-07-04 09:38 UTC, GiovanniMancini commented
@frtrinca I can't see changes made in the timeline reflected in the whole swagger for IO. Is this correct?

2023-07-05 08:30 UTC, GiovanniMancini approved these changes

2023-07-05 08:42 UTC, merged