fix: IDP-1645-Added 401 exception to wallet swagger api, modified swagger io full accordingly
pagopa/cstar-infrastructure pull request #1099
Opened 2023-08-29 10:03 UTC by SalvatorManna

### List of changes
Added 401 exception to wallet /wallet/{initiativeId}/detail api.
Modified swagger io full accordingly.

### Motivation and context
The api /wallet/{initiativeId}/detail was missing the 401 exception

### Type of changes

- [ ] Add new resources
- [X] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [X] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [X] No

#### Has This Been Tested?

- [X] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [X] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### If PR is partially applied, why? (reserved to mantainers)

2023-08-29 10:17 UTC, and-mora approved these changes

2023-08-29 10:33 UTC, mastro993 approved these changes

2023-08-29 17:29 UTC, and-mora requested changes
@SalvatorManna i noticed something strange and maybe you can clarify it.
There are 2 files: `openapi.wallet.yml` and `openapi.wallet.yml.tpl`. 
The first one is used as input in the DIFF merge script, [here](https://github.com/pagopa/cstar-infrastructure/blob/a6ec34ccdc56c3d8cc989f0f7b0411e4d1d7f0f4/scripts/idpay-script/openapi-merge.json#L34).
The second one is used in the api module, [here](https://github.com/pagopa/cstar-infrastructure/blob/a6ec34ccdc56c3d8cc989f0f7b0411e4d1d7f0f4/src/domains/idpay-app/04_apim_api_io.tf#L136).

In this PR you changed the first one and terraform shows NO changes in the plan (because it is not referenced in the API module).
As far as you know is there a reason to justify the presence of 2 openapi?

2023-08-30 07:35 UTC, SalvatorManna commented
> @SalvatorManna i noticed something strange and maybe you can clarify it. There are 2 files: `openapi.wallet.yml` and `openapi.wallet.yml.tpl`. The first one is used as input in the DIFF merge script, [here](https://github.com/pagopa/cstar-infrastructure/blob/a6ec34ccdc56c3d8cc989f0f7b0411e4d1d7f0f4/scripts/idpay-script/openapi-merge.json#L34). The second one is used in the api module, [here](https://github.com/pagopa/cstar-infrastructure/blob/a6ec34ccdc56c3d8cc989f0f7b0411e4d1d7f0f4/src/domains/idpay-app/04_apim_api_io.tf#L136).
> 
> In this PR you changed the first one and terraform shows NO changes in the plan (because it is not referenced in the API module). As far as you know is there a reason to justify the presence of 2 openapi?

That is not something I know.

2023-08-30 08:56 UTC, frtrinca commented
> @SalvatorManna i noticed something strange and maybe you can clarify it. There are 2 files: `openapi.wallet.yml` and `openapi.wallet.yml.tpl`. The first one is used as input in the DIFF merge script, [here](https://github.com/pagopa/cstar-infrastructure/blob/a6ec34ccdc56c3d8cc989f0f7b0411e4d1d7f0f4/scripts/idpay-script/openapi-merge.json#L34). The second one is used in the api module, [here](https://github.com/pagopa/cstar-infrastructure/blob/a6ec34ccdc56c3d8cc989f0f7b0411e4d1d7f0f4/src/domains/idpay-app/04_apim_api_io.tf#L136).
> 
> In this PR you changed the first one and terraform shows NO changes in the plan (because it is not referenced in the API module). As far as you know is there a reason to justify the presence of 2 openapi?

The correct swagger is openapi.wallet.yml.tpl
openapi.wallet.yml is used only to generate full swagger for IO, If we also change the swagger to the script that generates the full swagger, we could delete openapi.wallet.yml but we will check it in the future if the merge script works with .tpl files

2023-08-30 09:19 UTC, and-mora approved these changes

2023-08-30 09:20 UTC, petretiandrea approved these changes

2023-08-30 09:24 UTC, merged