feat: [IDP-2155] new fragment for MIL token
pagopa/cstar-infrastructure pull request #1196
Opened 2023-11-30 09:34 UTC by frtrinca

### List of changes
Add fragment for validate MIL token

### Motivation and context

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

#### Has This Been Tested?

- [x] Yes
- [ ] No

### Other information
Target: 
```
azapi_resource.apim-validate-token-mil
```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [x] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### If PR is partially applied, why? (reserved to mantainers)

2023-11-30 13:43 UTC, antonioT90 requested changes

2023-11-30 13:43 UTC, antonioT90 commented on src/domains/idpay-app/api_fragment/validate-token-mil.xml
> +  <set-variable name="idpayPortalToken" value="@{
here you are retrieving just the fiscalCode! chenge variable name, eg:
```suggestion
  <set-variable name="fiscalCode" value="@{
```

2023-11-30 13:43 UTC, antonioT90 commented on src/domains/idpay-app/env/prod/terraform.tfvars
> +openid_config_url_mil = "https://mil-u-apim.azure-api.net/mil-auth/.well-known/openid-configuration"
Let's ask what will be PROD value
```suggestion
openid_config_url_mil = "https://mil-p-apim.azure-api.net/mil-auth/.well-known/openid-configuration" #TODO to verify
```

2023-12-05 13:48 UTC, TommasoLencioni submitted a review, later dismissed

2023-12-05 13:53 UTC, lucaconsalvi submitted a review, later dismissed

2023-12-05 13:59 UTC, antonioT90 requested changes

2023-12-05 13:59 UTC, antonioT90 commented on src/domains/idpay-app/env/prod/terraform.tfvars
> +#TO CHANGE
```suggestion
#TODO: TO CHANGE
```

2023-12-05 14:10 UTC, antonioT90 approved these changes

2023-12-05 14:11 UTC, merged