feat: [IDP-2207] Added splitPayment and residualAmountCents on getStatusTransaction and Barcode authorization
pagopa/cstar-infrastructure pull request #1199
Opened 2023-12-12 14:31 UTC by stedelia

### List of changes

Added splitPayment and residualAmountCents on getStatusTransaction and Barcode authorization

### Motivation and context

### Type of changes

- [X] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [X] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [X] No

#### Has This Been Tested?

- [X] Yes
- [ ] No

### Other information
Target: 
```
module.idpay_merchants_portal
module.idpay_mil_payment
module.idpay_qr_code_payment_acquirer
module.idpay_qr_code_payment_mock_merchant

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [X] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### If PR is partially applied, why? (reserved to mantainers)

2023-12-14 09:49 UTC, frtrinca requested changes
L'assistenza non deve visualizzare queste nuove informazioni?

2023-12-14 10:39 UTC, stedelia commented
> L'assistenza non deve visualizzare queste nuove informazioni?

Updated assistance and merchant swaggers.

2023-12-14 11:19 UTC, frtrinca approved these changes

2023-12-15 09:07 UTC, TommasoLencioni approved these changes

2023-12-15 10:15 UTC, merged