feat: [IDP 2270] spostare coda timeline su evh01 e transaction su evh00
pagopa/cstar-infrastructure pull request #1218
Opened 2024-01-30 09:07 UTC by stedelia

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

#### Has This Been Tested?

- [ ] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [ ] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### If PR is partially applied, why? (reserved to mantainers)

2024-01-31 16:13 UTC, petretiandrea requested changes

2024-01-31 16:13 UTC, petretiandrea commented on src/domains/idpay-app/14_eventhub.tf
> +locals {
I think we can remove this part of "locals" and move `resource "azurerm_eventhub_namespace_authorization_rule" "evh_namespace_access_key_00"` and `
resource "azurerm_key_vault_secret" "event_hub_root_key_idpay_00"` to 13_config_kafka_connectors.tf which is strictly related to root access key

2024-02-02 13:23 UTC, petretiandrea approved these changes

2024-02-05 08:12 UTC, TommasoLencioni approved these changes

2024-02-05 08:12 UTC, TommasoLencioni approved these changes

2024-02-05 08:12 UTC, lucaconsalvi approved these changes

2024-02-05 08:12 UTC, merged