feat: [SRTP-98] add rtp activator in repo lists to federate azure
pagopa/cstar-infrastructure pull request #1331
Opened 2024-11-13 14:47 UTC by and-mora

This PR proposes to add the secrets related to azure federation in the github environment of `rtp-activator` 
### List of changes

### Motivation and context

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

#### Has This Been Tested?

- [ ] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [ ] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### If PR is partially applied, why? (reserved to mantainers)

2024-11-13 14:56 UTC, antoniotarricone requested changes
This should be in the rtp-app domain.

2024-11-14 08:38 UTC, and-mora commented
> This should be in the rtp-app domain.

should we duplicate the resources related to gh secrets (`github_actions_environment_secrets.tf`) and customize the configuration?

2024-11-14 09:06 UTC, antoniotarricone submitted a review, later dismissed

2024-11-15 11:23 UTC, TommasoLencioni approved these changes

2024-11-15 11:23 UTC, petretiandrea approved these changes

2024-11-15 11:24 UTC, merged