Fix api blobstorage
pagopa/cstar-infrastructure pull request #166
Opened 2021-09-14 15:37 UTC by uolter

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2021-09-14 15:38 UTC, uolter commented
Just applied in PROD

2021-09-15 08:46 UTC, pasqualedevita requested changes

2021-09-15 08:46 UTC, pasqualedevita commented on src/api.tf
> +        host = trim(azurerm_dns_a_record.dns_a_appgw_api.fqdn, ".")
```suggestion
        # as-is due an application error
        host = "prod.cstar.pagopa.it"
        # to-be
        # host = trim(azurerm_dns_a_record.dns_a_appgw_api.fqdn, ".")
```

2021-09-15 08:57 UTC, pasqualedevita approved these changes

2021-09-15 09:43 UTC, merged