[CEN-1282] Add cosmos db (mongo) with a transaction database
pagopa/cstar-infrastructure pull request #313
Opened 2022-01-21 16:27 UTC by GiovanniMancini

This PR proposes to add a Cosmos/Mongo account + a transaction DB to support ingestion pipeline of TAE application

### List of changes

- New Cosmos/Mongo account
- New Transaction DB
- New dedicated subnet
- New private dns zone to resolve private endpoint

### Motivation and context

This PR is required to have a scratch db where transactions can be ingested before aggregation for ADE

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-01-21 17:07 UTC, uolter commented on src/database.tf
> +  account_name        = module.cosmosdb_account_mongodb[count.index].name
it's ok, but since count can only assumes 0 or 1 .... it does not change that much.
It's a style exercise ;-)

2022-01-21 17:07 UTC, uolter submitted a review, later dismissed

2022-01-21 20:10 UTC, uolter commented on src/database.tf
> +  account_name        = module.cosmosdb_account_mongodb[count.index].name
@GiovanniMancini  mmmm well I changed my mind...
When count = 0 the resource **azurerm_cosmosdb_mongo_database.transaction** does not exist
while when count = 1 the resource exists but I feel module.cosmosdb_account_mongodb[1].name is throwing an error: the index 1 does not exist.
Am I wrong?

2022-01-24 14:40 UTC, pasqualedevita requested changes

2022-01-24 14:40 UTC, pasqualedevita commented on src/env/prod/terraform.tfvars
> +  backup_continuous_enabled = false
for production envs use continuous backup

2022-01-24 14:40 UTC, pasqualedevita commented on src/env/prod/terraform.tfvars
> +  capabilities = ["EnableMongo", "EnableServerless"]
```suggestion
  capabilities = ["EnableMongo"]
```
serverless is for dev/test envs. For production with heavy loads better use provisioned throughput

2022-05-19 10:04 UTC, diegolagospagopa submitted a review, later dismissed

2022-05-19 17:11 UTC, merged