add idpay eventhub
pagopa/cstar-infrastructure pull request #409
Opened 2022-06-23 13:42 UTC by dariopelliccioli

### List of changes

add eventhub namespace for idpay project

### Motivation and context

need to have async communication by queue between services

### Type of changes

- [X] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [X] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [] Yes
- [X] No

### Other information

The component have to be available only in DEV environment for now in order to contain infra costs.

---

### If PR is partially applied, why? (reserved to mantainers)

2022-06-23 13:45 UTC, pasqualedevita requested changes

2022-06-23 13:45 UTC, pasqualedevita commented on src/domains/idpay-common/04_eventhub.tf
> +  for_each = module.event_hub_idpay_01.key_ids
```suggestion
  for_each = module.event_hub_idpay_01[0].key_ids
```

2022-06-23 13:45 UTC, pasqualedevita commented on src/domains/idpay-common/04_eventhub.tf
> +  key_vault_id = module.key_vault_idpay.id
```suggestion
  key_vault_id = module.key_vault_idpay[0].id
```

2022-06-27 13:08 UTC, GiovanniMancini commented
/azp run cstar-infrastructure.code-review

2022-06-28 14:35 UTC, diegolagospagopa approved these changes

2022-06-28 15:18 UTC, merged