Added enrolled-pi eventhub connection uri to idpay kv
pagopa/cstar-infrastructure pull request #457
Opened 2022-07-22 12:14 UTC by petretiandrea

- This PR allow to create a connection uri string to idpay key vault in order to connect with enrolled-payment-instrument event hub

### List of changes

- added data source to get primary connection string from event hub
- added keyvault resource which format the connection string into a JAAS connection string

### Motivation and context

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-07-29 10:05 UTC, diegolagospagopa requested changes

2022-07-29 10:05 UTC, diegolagospagopa commented on src/domains/idpay-app/01_keyvault.tf
> +  value = format(
Please use the interpolation syntax

2022-07-29 10:05 UTC, diegolagospagopa commented on src/domains/idpay-app/env/dev/terraform.tfvars
> +}
Please enable in your editor the feature that allow to put an empty row in each file

2022-07-29 10:05 UTC, diegolagospagopa commented on src/domains/idpay-app/env/dev/terraform.tfvars
> +}
Please add the same value for UAT and PROD, to avoid problems during the apply

2022-07-29 13:03 UTC, petretiandrea commented on src/domains/idpay-app/01_keyvault.tf
> +  value = format(
Instead of format?

2022-07-29 15:10 UTC, diegolagospagopa commented on src/domains/idpay-app/01_keyvault.tf
> +  value = format(
Yes please

2022-07-29 15:59 UTC, petretiandrea commented on src/domains/idpay-app/01_keyvault.tf
> +  value = format(
Done

2022-08-01 12:17 UTC, GiovanniMancini commented
@petretiandrea Could you please resolve conflicts?

2022-08-02 09:33 UTC, merged