[RTD-374] Create new hashed pan container
pagopa/cstar-infrastructure pull request #483
Opened 2022-08-04 14:09 UTC by petretiandrea

This PR adds new container for hashed pans zip files.

### List of changes

- connected pipeline dataset to new container
- connected download hashpan apim to new container
- improved security for download hashpan apim by removing useless headers
- set lines for csv file to 4M (4.000.000)

### Motivation and context

### Type of changes

- [x] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

### Apply scopes
- `src` folder, only apim and storage resource -> `-target=azurerm_storage_container.cstar_hashed_pans -target=module.rtd_payment_instrument_manager_v2`
- `rtd-app`

2022-08-04 15:02 UTC, GiovanniMancini approved these changes

2022-08-08 05:47 UTC, GiovanniMancini commented
@petretiandrea we may need a flag on new container to avoid its provisioning in production. As far as I can see, `rtd domain` is not ready for production

2022-08-08 10:05 UTC, petretiandrea commented
> @petretiandrea we may need a flag on new container to avoid its provisioning in production. As far as I can see, `rtd domain` is not ready for production

Done

2022-08-08 12:52 UTC, petretiandrea commented
> > @petretiandrea we may need a flag on new container to avoid its provisioning in production. As far as I can see, `rtd domain` is not ready for production
> 
> @GiovanniMancini Done

2022-08-10 08:08 UTC, diegolagospagopa requested changes
Please check the variables for prod, because i think some one is not present

2022-08-10 08:08 UTC, diegolagospagopa commented on src/storage.tf
> +  count = var.enable.rtd.hashed_pans_container ? 1 : 0
Please put the count at the start of the resource

2022-08-10 08:08 UTC, diegolagospagopa commented on src/api_rtd.tf
>    name                = format("%s-rtd-payment-instrument-manager-api", var.env_short)
please use the string interpolation format

2022-08-10 08:37 UTC, diegolagospagopa approved these changes

2022-08-10 08:40 UTC, merged