[RTD-607] Change deposited file container in integration endpoint
pagopa/cstar-infrastructure pull request #576
Opened 2022-09-28 09:09 UTC by TommasoLencioni

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-09-29 12:51 UTC, diegolagospagopa requested changes

2022-09-29 12:51 UTC, diegolagospagopa commented on src/core/api_rtd.tf
> -    ade-in  = format("https://cstar%ssftp.blob.core.windows.net/ade/in/", var.env_short),
Please use the interpolation format

2022-09-29 12:51 UTC, diegolagospagopa commented on src/core/api/rtd_deposited_file_check/azureblob_policy.xml
> -
Do you think is better to put a comment with the issue, to simplify the futures updates?

2022-10-03 12:43 UTC, GiovanniMancini approved these changes

2022-10-03 12:44 UTC, merged