feat: [RTD-772] Add TAE pipeline failure alert
pagopa/cstar-infrastructure pull request #616
Opened 2022-10-20 14:14 UTC by TommasoLencioni

This PR proposes to add an alert triggered by Azure Data Factory failures metric.
### List of changes
- add alert

### Motivation and context
With this alert we can be notified through email if a pipeline fails.

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [x] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information
```
 --target="azurerm_monitor_metric_alert.tae_azure_data_factory_pipelines_failures[0]"
```

---

### If PR is partially applied, why? (reserved to mantainers)

2022-10-24 08:32 UTC, GiovanniMancini commented on src/domains/tae-app/00_monitor.tf
> +  description         = "Triggeer whenever at least one pipeline fails."
@TommasoLencioni  a small typo

2022-10-24 08:33 UTC, GiovanniMancini requested changes
@TommasoLencioni Just a small typo in alert description

2022-10-24 08:40 UTC, TommasoLencioni commented on src/domains/tae-app/00_monitor.tf
> +  description         = "Triggeer whenever at least one pipeline fails."
Fixed, thank you!

2022-10-26 12:31 UTC, GiovanniMancini approved these changes

2022-10-26 12:53 UTC, merged