feat: [IDP-177] Adding group/user lookup table to terraform
pagopa/cstar-infrastructure pull request #769
Opened 2023-01-16 16:31 UTC by marco-di-lisa

### List of changes

Added group_user_whitelist collection to IDPay database. The collection features two additional non-unique indexes (apart from the default unique _id): one on the groupId field, and another one on the userId field

### Motivation and context

This lookup collection has been added in order to prevent large (about > 90K userId) whitelists of userId strings to be written on a single document of the group collection, causing a 413 error, and a subsequent exception. 

### Type of changes

- [ ] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2023-01-20 11:54 UTC, marco-di-lisa commented
@mastro993 in the latest commit [20b5eb2] you will find the modifications to the Timeline Swagger

2023-01-20 13:18 UTC, mastro993 requested changes

2023-01-20 13:18 UTC, mastro993 commented on src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
>                  oneOf:
Shouldn't `oneOf` also be removed? It's already in `OperationDTO`

2023-01-30 11:07 UTC, GiovanniMancini approved these changes

2023-01-30 11:19 UTC, merged