feat: IDP-915-workbook-pagamenti
pagopa/cstar-infrastructure pull request #967
Opened 2023-06-08 12:22 UTC by LarissaASLeite

### List of changes

Add workbook Payment
Add Alert Onboarding Request

It's necessary to register the secret "alert-slack-idpay" in the key vault.

### Motivation and context

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [x] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

#### Has This Been Tested?

- [ ] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [ ] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### If PR is partially applied, why? (reserved to mantainers)

2023-06-08 12:45 UTC, antonioT90 requested changes

2023-06-08 12:45 UTC, antonioT90 commented on src/domains/idpay-app/01_keyvault.tf
> +  name         = "alert-slack-idpay"
let's use more significant name (aligned with already existent "alert-core-notification-slack")
```suggestion
  name         = "alert-idpay-notification-slack"
```

2023-06-08 12:45 UTC, antonioT90 commented on src/domains/idpay-app/12_alert.tf
> +  short_name          = "send_to_slack"
```suggestion
  short_name          = "send_to_idpay_slack"
```

2023-06-08 12:45 UTC, antonioT90 commented on src/domains/idpay-app/99_variables.tf
> +variable "idpay_alert_enabled" {
this structure is a waste, let's just define it as a simple boolean, having default value false
MoreOver, inside uat and prod (see env/* folders) you have to set this variable to true

2023-06-08 14:33 UTC, antonioT90 requested changes

2023-06-08 14:33 UTC, antonioT90 commented on src/domains/idpay-app/01_keyvault.tf
> +  count = var.idpay_alert_enabled.enable == true ? 1 : 0
```suggestion
  count = var.idpay_alert_enabled.enable ? 1 : 0
```

2023-06-08 14:33 UTC, antonioT90 commented on src/domains/idpay-app/12_alert.tf
> +  count = var.idpay_alert_enabled == true ? 1 : 0
```suggestion
  count = var.idpay_alert_enabled? 1 : 0
```

2023-06-08 15:12 UTC, antonioT90 requested changes

2023-06-08 15:12 UTC, antonioT90 commented on src/domains/idpay-app/12_alert.tf
> +  count = var.env_short == "p" ? 1 : 0
change this in order to check enable variable

2023-06-15 14:29 UTC, antonioT90 requested changes

2023-06-15 14:29 UTC, antonioT90 commented on src/domains/idpay-app/12_alert.tf
> +resource "azapi_resource" "CosmosServerSideRetry" {
```suggestion
resource "azapi_resource" "alert_CosmosServerSideRetry" {
```

2023-06-15 14:29 UTC, antonioT90 commented on src/domains/idpay-app/env/uat/terraform.tfvars
> +idpay_alert_enabled = true
this is repeated twice in this file

2023-06-16 10:21 UTC, GiovanniMancini submitted a review, later dismissed

2023-06-16 10:38 UTC, merged